name: Angular CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.11.0'  # Update this to match your local Node.js version
      
    - name: Install dependencies
      run: npm install
      
    - name: Build Angular app
      run: ng build --prod
      
    - name: Run tests
      run: ng test --watch=false
